name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    # Requires newer gtk-4 than what's available in default 22.04, therefore using docker
    container: ubuntu:24.04

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      
      - name: Install deps
        run: |
          apt update
          apt install -y libgtk-4-dev rustup meson gettext blueprint-compiler desktop-file-utils

      - run: rustup update stable && rustup default stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - run: meson setup build
      - run: meson install -C build
      - run: cargo test --verbose

      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
